
name: CD - dbt Prod on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  run-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install dbt-snowflake

      - name: Copy profiles.yml to ~/.dbt
        run: |
          mkdir -p ~/.dbt
          cp .finconfig/profiles.yml ~/.dbt/profiles.yml

      - name: Run dbt in production
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          dbt deps --target prod
          dbt seed --target prod
          dbt run --target prod
          dbt test --target prod
        working-directory: ./FinData
