name: CI - dbt Dev and Test Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Copy profiles.yml to ~/.dbt
        run: |
          mkdir -p ~/.dbt
          cp .finconfig/profiles.yml ~/.dbt/profiles.yml

      - name: Run dbt in dev environment
        run: |
          dbt deps --target dev
          dbt seed --target dev
          dbt run --target dev
          dbt test --target dev
        working-directory: ./FinData
      
      - name: Run dbt in test environment
        run: |
          dbt deps --target testing
          dbt run --target testing
          dbt test --target testing
        working-directory: ./FinData
      
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
